### ISSUE TITLE
rainbowkit-plugin incompatible with newer `0xsequence` package

### ISSUE THREAD

**Issue by KholdStare** [0xsequence/rainbowkit-plugin#10]
Newest `0xsequence` requires `projectAccessKey` as first parameter to `initWallet`:

https://github.com/0xsequence/sequence.js/blob/master/packages/provider/src/init.ts#L69

However it is missing from the call in the plugin here:

https://github.com/0xsequence/rainbowkit-plugin/blob/master/src/sequence-connector.ts#L33-L39

Perhaps this needs a major version bump to change the peer dependency?

**Comment by SamueleA** [comment]
This should now work properly with version 2.1.7
